name: CI/CD

# When the workflow will run, in this case
# on push or pull request to the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  PUBLIC_VITE_APIKEY: AIzaSyCcgKN9R58V-SUH_xUxg-ipWuCksU6HUTw
  PUBLIC_VITE_AUTH_DOMAIN: task-management-app-3efab.firebaseapp.com
  PUBLIC_VITE_PROJECT_ID: task-management-app-3efab
  PUBLIC_VITE_STORAGE_BUCKET: task-management-app-3efab.appspot.com
  PUBLIC_VITE_MESSAGING_SENDER_ID: 643729535026
  PUBLIC_VITE_APP_ID: 1:643729535026:web:c663bc3cce968316580c2b
  PUBLIC_VITE_MEASUREMENT_ID: G-GGQ2WZVVF5
# Jobs are a sequence of steps
jobs:
  # This workflow has only one Job, build
  build:
    # The type of container the workflow will run on 
    runs-on: ubuntu-latest

    # The sequence of steps for this job
    steps:
    # Checks-out your repository so your job can access it
    - uses: actions/checkout@v2

    # First install dependencies for the front end and then 
    # for the cloud function. If you only have frontend remove the lines 
    # from after "npm run build" till the next step i.e. "Firebase Deploy"
    - name: Build
      run: |
        cd task-management-app
        npm i
        npm run build
    # Install firebase tools and deploy to firebase
    # using the token we created earlier
    - name: Firebase Deploy
      run: |
        cd task-management-app
        npm install -g firebase-tools
        firebase experiments:enable webframeworks
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
